spring:
  security:
    user:
      name: user
      password: password

  datasource:
    url: jdbc:mysql://localhost:3306/blog_application
    username: root
    password: Apple10293847
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB



logging:
  level:
    org.springframework.security: DEBUG